### ISSUE TITLE
[1.1.2] NRE on part load

### ISSUE THREAD

**Issue by KSAMissionCtrl** [Angel-125/Buffalo#2]
Using the latest release, this nullref appears in the log when just CRP, MM and Squad are also installed

    [LOG 23:16:45.229] PartLoader: Part 'WildBlueIndustries/Buffalo/Parts/Utility/Wagon2u/WBI_Wagon2u' has no database record. Creating.
    [LOG 23:16:45.234] DragCubeSystem: Creating drag cubes for part 'WBI.Wagon2u'
    [EXC 23:16:45.237] NullReferenceException: Object reference not set to an instance of an object
      ModuleDeployableSolarPanel.AssumeDragCubePosition (System.String name)
      DragCubeSystem+<RenderDragCubes>c__IteratorC.MoveNext ()
      UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
      <RenderDragCubesCoroutine>c__IteratorB:MoveNext()
      UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
      <SetupDragCubeCoroutine>c__IteratorD:MoveNext()
      UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
      <CompileParts>c__Iterator4A:MoveNext()

[output_log.txt](https://github.com/Angel-125/Buffalo/files/248109/output_log.txt)

**Comment by Angel-125** [comment]
Fixed in latest Buffalo. :)
